export default {
  key: "es",
  login: "Iniciar Sesión",
  username: "Nombre de Usuario",
  password: "Contraseña",
  all_fields_required: "Todos los campos son obligatorios",
  access: "Ingresar",
  accept: "Aceptar",
  home: "Inicio",
  sellers: "Vendedores",
  orders: "Pedidos",
  articles: "Articulos",
  article: "Articulo",
  reports: "Reportes",
  goals: "Metas",
  inventory: "Inventario",
  warehouses: "Almacenes",
  warehouse: "Almacen",
  "article-groups": "Grupos de Articulos",
  visits: "Visitas",
  users: "Usuarios",
  images: "Imagenes",
  clients: "Clientes",
  id: "ID",
  identifyer: "Identificador",
  system: "Sistema",
  permissions: "Permisos",
  name: "Nombre",
  document: "N. Documento",
  invoice: "Factura",
  code: "Codigo",
  info: "Información",
  type: "Tipo",
  consultant: "Asesor",
  seller: "Vendedor",
  image: "Imagen",
  qty_stipulated: "Cantidad estipulada",
  qty: "Cantidad",
  percent: "Porcentaje",
  progress: "Progreso",
  lines: "Lineas",
  start: "Inicio",
  end: "Finalización",
  yes: "Si",
  no: "No",
  back: "Volver",
  create_goal: "Crear Meta",
  see_details: "Ver detalle",
  start_date: "Fecha de inicio",
  finish_date: "Fecha de finalización",
  from_date: "Fecha desde",
  to_date: "Fecha hasta",
  from_date_authorized: "Fecha de autorización (desde)",
  to_date_authorized: "Fecha de autorización (hasta)",
  add_line: "Añadir linea",
  are_u_sure: "¿Estas seguro?",
  im_sure: "Estoy seguro",
  this_action_cannot_be_undone: "Esta acción no se puede deshacer",
  goal_type: "Tipo de Meta",
  qty_or_percent: "Cantidad o Porcentaje",
  select_seller: "Seleccionar Vendedor",
  select_article_group: "Seleccionar grupo de articulos",
  select_brand: "Seleccionar marca",
  select_category: "Seleccionar categoria",
  select_subcategory: "Seleccionar subcategoria",
  select_articles: "Seleccionar articulos",
  select_article: "Seleccionar articulo",
  select_bank: "Seleccionar banco",
  select_supplier: "Seleccionar proveedor",
  n_articles: "N°. Articulos",
  value: "Valor",
  activation: "Activación",
  article_group_id: "Grupo de articulos",
  brand: "Marca",
  category: "Categoria",
  categories: "Categorias",
  subcategory: "Subcategoria",
  subcategories: "Subcategorias",
  create_category: "Crear Categoria",
  code_category: "Codigo de Categoria",
  create_subcategory: "Crear Subcategoria",
  code_subcategory: "Codigo de Subcategoria",
  sucess: "Exitoso",
  success_created_category: "Categoria creada correctamente",
  error_created_category: "Error al crear la categoria",
  success_updated_category: "Categoria actualizada correctamente",
  error_updated_category: "Error al actualizar la categoria",
  edit_category: "Editar Categoria",
  delete_category: "Eliminar Categoria",
  confirm_delete_category: "¿Esta seguro que desea eliminar esta categoria?",
  success_deleted_category: "Categoria eliminada correctamente",
  error_deleted_category: "Error al eliminar la categoria",
  success_editted_category: "Categoria editada correctamente",
  error_editted_category: "Error al editar la categoria",
  success_created_subcategory: "Subcategoria creada correctamente",
  error_created_subcategory: "Error al crear la Subcategoria",
  success_updated_subcategory: "Subcategoria actualizada correctamente",
  error_updated_subcategory: "Error al actualizar la Subcategoria",
  edit_subcategory: "Editar Subcategoria",
  delete_subcategory: "Eliminar Subcategoria",
  confirm_delete_subcategory:
    "¿Esta seguro que desea eliminar esta Subcategoria?",
  success_deleted_subcategory: "Subcategoria eliminada correctamente",
  error_deleted_subcategory: "Error al eliminar la Subcategoria",
  success_editted_subcategory: "Subcategoria editada correctamente",
  error_editted_subcategory: "Error al editar la Subcategoria",
  articles_selected: "Articulos seleccionados",
  article_id: "Articulo",
  selected: "Seleccionado/s",
  select_goal_type: "Seleccionar tipo de meta",
  save: "Guardar",
  cancel: "Cancelar",
  create: "Crear",
  error_no_seller: "Debe seleccionar un vendedor",
  error_no_article_group: "Debe seleccionar un grupo de articulos",
  error_no_brand: "Debe seleccionar una marca",
  error_no_category: "Debe seleccionar una categoria",
  error_no_articles: "Debe seleccionar articulos",
  error_no_article: "Debe seleccionar un articulo",
  error_no_start_date: "Debe seleccionar una fecha de inicio",
  error_no_finish_date: "Debe seleccionar una fecha de finalización",
  error_no_qty_stipulated: "Debe ingresar una cantidad estipulada",
  error_no_goal_type: "Debe seleccionar un tipo de meta",
  error_no_lines: "Debe añadir al menos una linea",
  success_created_goal: "Meta creada correctamente",
  error_created_goal: "Error al crear la meta",
  edit_goal: "Editar Meta",
  success_updated_goal: "Meta actualizada correctamente",
  error_updated_goal: "Error al actualizar la meta",
  delete_goal: "Eliminar Meta",
  confirm_delete_goal: "¿Esta seguro que desea eliminar esta meta?",
  success_deleted_goal: "Meta eliminada correctamente",
  error_deleted_goal: "Error al eliminar la meta",
  total_progress: "Progreso total",
  total: "Total",
  goal_details: "Detalles de la meta",
  loading: "Cargando...",
  no_results: "No se encontraron resultados",
  confirm: "Confirmar",
  delete: "Eliminar",
  edit: "Editar",
  view: "Ver",
  actions: "Acciones",
  search: "Buscar",
  date: "Fecha",
  creation_date: "Fecha de Creación",
  create_visit: "Crear Visita",
  client: "Cliente",
  select_client: "Seleccionar cliente",
  error_no_client: "Debe seleccionar un cliente",
  success_created_visit: "Visita creada correctamente",
  error_created_visit: "Error al crear la visita",
  edit_visit: "Editar Visita",
  success_updated_visit: "Visita actualizada correctamente",
  error_updated_visit: "Error al actualizar la visita",
  delete_visit: "Eliminar Visita",
  confirm_delete_visit: "¿Esta seguro que desea eliminar esta visita?",
  success_deleted_visit: "Visita eliminada correctamente",
  error_deleted_visit: "Error al eliminar la visita",
  visit_details: "Detalles de la visita",
  check_in: "Registrar entrada",
  description: "Descripción",
  comment: "Comentario",
  reason: "Motivo",
  add: "Agregar",
  add_image: "Agregar imagen",
  price_list: "Lista de precios",
  no_images: "No hay imagenes",
  no_items: "No hay datos que mostrar",
  select_image: "Seleccionar imagen",
  error_no_image: "Debe seleccionar una imagen",
  price: "Precio",
  article_group: "Grupo de Articulos",
  create_article_group: "Crear Grupo de Articulos",
  article_groups: "Grupos de Articulos",
  view_index: "Orden de Visualización",
  sku: "SKU",
  edit_article: "Editar Articulo",
  success_updated_article: "Articulo actualizado correctamente",
  error_updated_article: "Error al actualizar el articulo",
  edit_articles_group: "Editar Grupo de Articulos",
  up: "Subir en el Orden de Visualización",
  down: "Bajar en el Orden de Visualización",
  discount_min: "Descuento minimo",
  discount_max: "Descuento maximo",
  discount: "Descuento",
  error_created_article_group: "Error al crear el grupo de articulos",
  success_created_article_group: "Grupo de articulos creado correctamente",
  error_editted_article_group: "Error al editar el grupo de articulos",
  success_editted_article_group: "Grupo de articulos editado correctamente",
  set_articles_to_article_group: "Asignar articulos al grupo de articulos",
  success_set_updated_article_group:
    "Grupo de articulos asignado correctamente",
  error_set_updated_article_group: "Error al asignar el grupo de articulos",
  units: "Unidades",
  stock: "Stock",
  withstock: "Con Stock",
  nostock: "Sin Stock",
  all: "Todos",
  seller_name: "Nombre del Vendedor",
  seller_document: "Documento del Vendedor",
  consultant_name: "Nombre del Asesor",
  consultant_document: "Documento del Asesor",
  clients_map: "Mapa de Clientes",
  visits_map: "Mapa de Visitas",
  orders_map: "Mapa de Pedidos",
  is_admin: "Administrador",
  assign: "Asignar Permiso: ",
  unnasign: "Desasignar Permiso: ",
  success_updated_user: "Usuario actualizado correctamente",
  error_updated_user: "Error al actualizar el usuario",
  edit_user: "Editar Usuario",
  select_sellers: "Seleccionar Vendedores",
  password_placeholder: "Contraseña (dejar vacio para no modificar)",
  error_no_username: "Debe ingresar un nombre de usuario",
  error_no_password: "Debe ingresar una contraseña",
  error_password_length: "La contraseña debe tener al menos 8 caracteres",
  create_user: "Crear Usuario",
  success_created_user: "Usuario creado correctamente",
  error_created_user: "Error al crear el usuario",
  status: "Status",
  active: "Activo",
  inactive: "Inactivo",
  activate_user: "Activar Usuario",
  deactivate_user: "Desactivar Usuario",
  no_clients_with_lat_and_long: "No hay clientes con Ubicación disponible",
  discount_defaults: "Descuentos predeterminados",
  discount_defaults_example: "Ej: 0,10,15 (Separados por coma)",
  date_range: "Rango de fechas",
  to: "Hasta",
  from: "Desde",
  refresh_map_filtered: "Actualizar mapa con datos filtrados",
  assigned_clients: "Clientes asignados",
  seller_detail: "Detalle de vendedor",
  goal_detail: "Detalle de meta",
  email: "Correo Electronico",
  language: "Idioma",
  dark_mode: "Modo oscuro",
  default_price: "Precio predeterminado",
  printed: "Impreso",
  client_code: "Codigo de Cliente",
  client_name: "Cliente",
  print_order: "Imprimir Orden de Venta",
  cancel_order: "Cancelar pedido",
  approve_date: "Fecha de aprobación",
  pending: "Pendiente",
  per_upload: "Pendiente Sync",
  uploaded: "Enviada",
  pre_processed: "Parcialmente procesada",
  processed: "Procesada",
  canceled: "Cancelado",
  rejected: "Rechazado",
  order_details: "Detalle del pedido",
  article_name: "Nombre Articulo",
  sure_cancel_order: "¿Está seguro que desea cancelar este pedido?",
  order_canceled: "Pedido cancelado correctamente",
  selected_title: "Seleccionados",
  no_selected_title: "No Seleccionados",
  model: "Modelo de Datos",
  record: "Registro",
  user: "Usuario",
  nothing_here: "Ups, parece que no hay nada aqui...",
  approver: "Aprobador",
  latitude: "Latitud",
  longitude: "Longitud",
  success_deleted_article_group: "Grupo de articulos eliminado correctamente",
  sure_delete_location: "¿Está seguro que desea eliminar esta ubicación?",
  location_deleted: "Ubicación eliminada correctamente",
  delete_location: "Eliminar ubicación",
  has_location: "Ubicación disponible",
  client_level: "Nivel de Cliente",
  level: "Nivel",
  update_client: "Actualizar Cliente",
  success_updated_client: "Cliente actualizado correctamente",
  error_updated_client: "Error al actualizar el cliente",
  print_ranking: "Imprimir Ranking",
  error_no_date: "Debe colocar las fechas solicitadas",
  start_time: "Inicio",
  end_time: "Finalización",
  total_deactivated: "Desactivados",
  total_updated: "Actualizados",
  total_inserted: "Insertados",
  process: "Proceso",
  banks: "Bancos",
  bank: "Banco",
  currencies: "Monedas",
  code_currency: "Código de la moneda",
  create_currency: "Crear Moneda",
  success_created_currency: "Moneda creada correctamente",
  error_created_currency: "Error al crear la moneda",
  success_updated_currency: "Moneda actualizada correctamente",
  error_updated_currency: "Error al actualizar la moneda",
  edit_currency: "Editar Moneda",
  delete_currency: "Eliminar Moneda",
  confirm_delete_currency: "¿Esta seguro que desea eliminar esta moneda?",
  success_deleted_currency: "Moneda eliminada correctamente",
  error_deleted_currency: "Error al eliminar la moneda",
  success_editted_currency: "Moneda editada correctamente",
  error_editted_currency: "Error al editar la moneda",
  code_bank: "Código del banco",
  account_number: "Número de cuenta",
  success_created_bank: "Banco creado correctamente",
  error_created_bank: "Error al crear el banco",
  success_updated_bank: "Banco actualizado correctamente",
  error_updated_bank: "Error al actualizar el banco",
  delete_bank: "Eliminar Banco",
  confirm_delete_bank: "¿Esta seguro que desea eliminar este banco?",
  success_deleted_bank: "Banco eliminado correctamente",
  error_deleted_bank: "Error al eliminar el banco",
  create_bank: "Crear Banco",
  success_editted_bank: "Banco editado correctamente",
  error_editted_bank: "Error al editar el banco",
  rate: "Tasa",
  create_rate: "Crear Tasa",
  success_created_rate: "Tasa creada correctamente",
  error_created_rate: "Error al crear la tasa",
  success_updated_rate: "Tasa actualizada correctamente",
  error_updated_rate: "Error al actualizar la tasa",
  edit_rate: "Editar Tasa",
  delete_rate: "Eliminar Tasa",
  confirm_delete_rate: "¿Esta seguro que desea eliminar esta tasa?",
  success_deleted_rate: "Tasa eliminada correctamente",
  error_deleted_rate: "Error al eliminar la tasa",
  companies: "Compañías",
  company: "Compañia",
  code_company: "Código de la compañía",
  active_company: "Estatus",
  question_active: "¿Activo?",
  create_company: "Crear Compañía",
  success_created_company: "Compañía creada correctamente",
  error_created_company: "Error al crear la compañía",
  success_updated_company: "Compañía actualizada correctamente",
  error_updated_company: "Error al actualizar la compañía",
  edit_company: "Editar Compañía",
  delete_company: "Eliminar Compañía",
  confirm_delete_company: "¿Esta seguro que desea eliminar esta compañía?",
  success_deleted_company: "Compañía eliminada correctamente",
  error_deleted_company: "Error al eliminar la compañía",
  success_editted_company: "Compañía editada correctamente",
  error_editted_company: "Error al editar la compañía",
  suppliers: "Proveedores",
  code_supplier: "Código del proveedor",
  create_supplier: "Crear Proveedor",
  success_created_supplier: "Proveedor creado correctamente",
  exist_supplier:
    "El proveedor ya existe, se ha creado una solicitud de aprobación para el mismo",
  error_created_supplier: "Error al crear el proveedor",
  success_updated_supplier: "Proveedor actualizado correctamente",
  error_updated_supplier: "Error al actualizar el proveedor",
  edit_supplier: "Editar Proveedor",
  delete_supplier: "Eliminar Proveedor",
  confirm_delete_supplier: "¿Esta seguro que desea eliminar este proveedor?",
  success_deleted_supplier: "Proveedor eliminado correctamente",
  error_deleted_supplier: "Error al eliminar el proveedor",
  success_editted_supplier: "Proveedor editado correctamente",
  error_editted_supplier: "Error al editar el proveedor",
  manager: "Encargado",
  auditor: "Auditor",
  phone: "Teléfono",
  created_user: "Usuario Creador",
  active_supplier: "Estatus",
  create_department: "Crear departamento",
  success_created_department: "Departamento creado correctamente",
  error_created_department: "Error al crear el departamento",
  success_editted_department: "Departamento editado correctamente",
  error_editted_department: "Error al editar el departamento",
  authorized_user: "Encargado",
  creator_name: "Nombre del creador",
  departments: "Departamentos",
  see_accounts: "Ver Cuentas",
  bank_data: "Datos bancarios",
  success_bank_edit_supplier: "Proveedor bancario editado correctamente",
  error_bank_edit_supplier: "Error al editar el proveedor bancario",
  success_deleted_bank_supplier:
    "Cuenta bancaria del proveedor eliminada correctamente",
  error_deleted_bank_supplier:
    "Error al eliminar la cuenta bancaria del proveedor",
  create_bank_account: "Crear Cuenta Bancaria",
  success_created_bank_account: "Cuenta bancaria creada correctamente",
  error_created_bank_account: "Error al crear la cuenta bancaria",
  select_authorized_user: "Seleccionar encargado",
  none: "Ninguno",
  rol: "Rol",
  paymaster: "Pagador",
  admin: "Administrador",
  requests: "Solicitudes",
  create_request: "Crear Solicitud",
  success_created_request: "Solicitud creada correctamente",
  error_created_request: "Error al crear la solicitud",
  edit_request: "Editar Solicitud",
  success_updated_request: "Solicitud actualizada correctamente",
  error_updated_request: "Error al actualizar la solicitud",
  delete_request: "Eliminar Solicitud",
  confirm_delete_request: "¿Esta seguro que desea eliminar esta solicitud?",
  success_deleted_request: "Solicitud eliminada correctamente",
  error_deleted_request: "Error al eliminar la solicitud",
  success_editted_request: "Solicitud editada correctamente",
  error_editted_request: "Error al editar la solicitud",
  success_approved_request: "Solicitud aprobada correctamente",
  error_approved_request: "Error al aprobar la solicitud",
  success_preapproved_request: "Solicitud pre-aprobada correctamente",
  error_preapproved_request: "Error al pre-aprobar la solicitud",
  success_rejected_request: "Solicitud rechazada correctamente",
  error_rejected_request: "Error al rechazar la solicitud",
  success_canceled_request: "Solicitud cancelada correctamente",
  error_canceled_request: "Error al cancelar la solicitud",
  success_reviewed_request: "Solicitud revisada correctamente",
  error_reviewed_request: "Error al revisar la solicitud",
  title: "Título",
  amount: "Monto",
  approver_name: "Aprobador",
  created_date: "Fecha de Creación",
  authorized_date: "Fecha de Autorización",
  approved_date: "Fecha de Aprobación",
  payouts: "Pagos",
  create_payout: "Crear Pago",
  success_created_payout: "Pago creado correctamente",
  error_created_payout: "Error al crear el pago",
  edit_payout: "Editar Pago",
  success_updated_payout: "Pago actualizado correctamente",
  error_updated_payout: "Error al actualizar el pago",
  delete_payout: "Eliminar Pago",
  confirm_delete_payout: "¿Esta seguro que desea eliminar este pago?",
  success_deleted_payout: "Pago eliminado correctamente",
  error_deleted_payout: "Error al eliminar el pago",
  success_editted_payout: "Pago editado correctamente",
  error_editted_payout: "Error al editar el pago",
  photo_request: "Foto de la Solicitud",
  department: "Departamento",
  see_departments: "Ver Departmentos",
  dept: "Dept.",
  currency: "Moneda",
  supplier: "Proveedor",
  supplier_bank: "Banco proveedor",
  no_banks_registered: "No hay bancos registrados a este proveedor.",
  approved: "Aprobado",
  preapproved: "Pre-aprobado",
  paid: "Pagado",
  approve: "Aprobar",
  preapprove: "Pre-Aprobar",
  reject: "Rechazar",
  authorize: "Autorizar",
  authorized: "Autorizado",
  reviewed: "Revisado",
  review: "Revisar",
  add_payout: "Agregar pago",
  confirm_preapprove: "¿Está seguro que desea pre-aprobar esta solicitud?",
  confirm_approve: "¿Está seguro que desea aprobar esta solicitud?",
  confirm_cancel: "¿Está seguro que desea cancelar esta solicitud?",
  confirm_reject: "¿Está seguro que desea rechazar esta solicitud?",
  confirm_review: "¿Está seguro que desea marcar esta solicitud como revisada?",
  generate_payment: "Generar Pago",
  create_payment: "Crear Pago",
  success_created_payment: "Pago creado correctamente",
  photo_reference: "Comprobante",
  bank_reference: "Referencia bancaria",
  created_by: "Creado por",
  authorized_by: "Autorizado por",
  approved_by: "Aprobado por",
  see_pays: "Ver pagos",
  success: "Éxito",
  see_photo: "Ver cotización",
  download_photo: "Descargar cotización",
  error_fetching_photo: "Error al obtener la foto de la solicitud",
  photo_not_available: "Foto de la solicitud no disponible",
  fast_actions: "Acciones rápidas",
  my_requests: "Mis Solicitudes",
  last_pays: "Últimos pagos",
  invalid_amount: "Monto invalido",
  category_subcategory_department: "Compañia / Cat. / Subcat. / Depart.",
  select_manager: "Seleccione un encargado",
  options: "Opciones",
  supplier_approvals: "Aprobación de Proveedores",
  credit_limit: "Limite de credito",
  have_supplier_approvals: "Tienes aprobaciones de proveedores pendientes",
  exist_bank_supplier: "Proveedor ya tiene banco registrado.",
  document_type: "Tipo de documento",
  select_document_type: "Seleccionar tipo de documento",
  error_approving_supplier: "Error al aprobar el proveedor",
  error_rejecting_supplier: "Error al rechazar el proveedor",
  download_image: "Descargar imagen",
  support: "Soporte",
  generate_file: "Generar archivo",
  banesco_file_config: "Configuración archivo Banesco",
  company_name: "Nombre de la empresa",
  rif: "RIF",
  debit_account: "Cuenta débito",
  batch_reference: "Referencia de lote",
  gestion_type: "Tipo de gestión",
  file_generated: "Archivo generado correctamente",
  error_generating_file: "Error al generar el archivo",
  amount_ves: "Monto en Bs",
  amount_usd: "Monto en USD",
  total_usd: "Total en USD",
  total_ves: "Total en Bs",
  export_excel: "Exportar a Excel",
  select_at_least_one_to_export:
    "Debe seleccionar al menos una fila para exportar",
  select_all: "Seleccionar todo",
  file_added: "En txt",
  some_requests_already_generated: "Algunas solicitudes ya fueron generadas",
  continue_anyway: "Continuar igualmente",
  parent_category: "Categoria padre",
  total_efc: "Total EFC",
  total_bcv: "Total BCV",
  total_bs: "Total BS",
  efective: "Efectivo",
  error_fetching_requests: "Error al obtener las solicitudes",
  error_fetching_banks: "Error al obtener los bancos",
  pending_for_preapprove: "1. Pendiente",
  pending_for_review: "2. Pend. de revisión",
  pending_for_approve: "3. Pend. de aprobación",
  pending_for_pay: "4. Pend. de pago",
  paid_tab: "5. Pagado",
  variables: "Variables",
  no_variables: "No hay variables para mostrar",
  add_variable: "Agregar variable",
  multiple: "Multiples",
  dependency: "Dependencia",
  query_1: "Query 1",
  query_2: "Query 2",
  requests_statuses: "Estados de las solicitudes (Acceso directo)",
  daily_report: "Reporte diario",
  paste_image_here: "Pegar imagen aquí",
  save_report: "Guardar reporte",
  import_template: "Importar plantilla",
  export_template: "Exportar plantilla",
  confirm_delete_report: "¿Estas seguro de eliminar el reporte?",
  cancel_editing: "Cancelar edición",
  update_report: "Actualizar reporte",
  editing_report_id: "Editando reporte ID",
  saved_reports: "Reportes guardados",
  reload: "Recargar",
  loading_reports: "Cargando reportes...",
  no_reports_created: "No hay reportes creados",
  generate: "Generar",
  show_report_builder: "Mostrar creador de reportes",
  hide_report_builder: "Ocultar creador de reportes",
  allow_multiple_values: "Permitir multiples valores",
  paste_template_json_here: "Pega aqui el JSON de la plantilla",
  invalid_template_json: "El JSON de la plantilla es invalido",
  template_imported_success: "Plantilla importada correctamente",
  report_json_copied: "JSON del reporte copiado al portapapeles",
  failed_to_parse_template_json:
    "No se pudo interpretar el JSON de la plantilla",
  error_copying_report_json: "No se pudo copiar el JSON del reporte",
  error_loading_reports: "Error al cargar reportes",
  missing_required_fields_create_report:
    "Faltan campos obligatorios para crear el reporte",
  report_created_success: "Reporte creado correctamente",
  error_creating_report: "Error al crear el reporte",
  must_select_report_to_edit: "Debes seleccionar un reporte para editar",
  missing_required_fields_update_report:
    "Faltan campos obligatorios para actualizar el reporte",
  report_updated_success: "Reporte actualizado correctamente",
  error_updating_report: "Error al actualizar el reporte",
  report_deleted_success: "Reporte eliminado correctamente",
  error_deleting_report: "Error al eliminar el reporte",
  report_executed_success: "Reporte ejecutado correctamente",
  error_executing_report: "Error al ejecutar el reporte",
  confirm_run_report_test:
    "¿Estas seguro de ejecutar este reporte? Esto va a guardar los cambios realizados en el reporte si es que no se han guardado aún.",
  error_fetching_reason: "Error al obtener los motivos de rechazo",
  see_reason: "Ver motivo de rechazo",
  no_reason_available: "No hay motivo de rechazo disponible",
  no_reject_motives: "No hay motivos de rechazo",
  unique: "Clave única",
  copied: "Copiado",
  multi_requests: "Multi solicitudes",
  error_updated_multi_requests:
    "Error al actualizar multi solicitudes a proveedor",
  success_updated_multi_requests:
    "Multi solicitudes de proveedor actualizadas correctamente",
  orientation: "Orientación",
  portrait: "Vertical",
  landscape: "Horizontal",
  outputType: "Tipo de salida",
  pdf: "PDF",
  excel: "Excel",
  error_created_bank_supplier: "Debe colocar un banco para el proveedor",
  invalid_document_supplier: "Documento invalido para el tipo de documento seleccionado (9 Digitos para RIF Juridico o Gubernamental)",
  table: "Tabla",
  image_too_large: "(Error): Imagen demasiado grande",
  olts: "OLTs",
  create_olt: "Crear OLT",
  success_created_olt: "OLT creado correctamente",
  error_created_olt: "Error al crear la OLT",
  edit_olt: "Editar OLT",
  success_updated_olt: "OLT actualizado correctamente",
  error_updated_olt: "Error al actualizar la OLT",
  delete_olt: "Eliminar OLT",
  confirm_delete_olt: "¿Esta seguro que desea eliminar esta OLT?",
  success_deleted_olt: "OLT eliminado correctamente",
  error_deleted_olt: "Error al eliminar la OLT",
  success_editted_olt: "OLT editado correctamente",
  error_editted_olt: "Error al editar la OLT",
  mikrotiks: "Mikrotiks",
  create_mikrotik: "Crear Mikrotik",
  success_created_mikrotik: "Mikrotik creado correctamente",
  error_created_mikrotik: "Error al crear el Mikrotik",
  edit_mikrotik: "Editar Mikrotik",
  success_updated_mikrotik: "Mikrotik actualizado correctamente",
  error_updated_mikrotik: "Error al actualizar el Mikrotik",
  delete_mikrotik: "Eliminar Mikrotik",
  confirm_delete_mikrotik: "¿Esta seguro que desea eliminar este Mikrotik?",
  success_deleted_mikrotik: "Mikrotik eliminado correctamente",
  error_deleted_mikrotik: "Error al eliminar el Mikrotik",
  success_editted_mikrotik: "Mikrotik editado correctamente",
  error_editted_mikrotik: "Error al editar el Mikrotik",
  plans: "Planes",
  create_plan: "Crear Plan",
  details: "Detalles",
  success_created_plan: "Plan creado correctamente",
  error_created_plan: "Error al crear el plan",
  success_updated_plan: "Plan actualizado correctamente",
  error_updated_plan: "Error al actualizar el plan",
  edit_plan: "Editar Plan", 
};
